wandb_version: 1

batch_size:
  value: 128
beam_size:
  value: 3
cell_type:
  value: rnn
decoder_dropout:
  value: 0.1
embedding_size:
  value: 32
encoder_dropout:
  value: 0.5
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
num_layers:
  value: 3
