wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 7
cell_type:
  value: gru
decoder_dropout:
  value: 0.1
embedding_size:
  value: 64
encoder_dropout:
  value: 0.3
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
num_layers:
  value: 1
