wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: null
cell_type:
  value: lstm
decoder_dropout:
  value: 0.3
embedding_size:
  value: 256
encoder_dropout:
  value: 0.4
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_decoder_layers:
  value: 3
num_encoder_layers:
  value: 1
