wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 7
cell_type:
  value: lstm
decoder_dropout:
  value: 0.5
embedding_size:
  value: 64
encoder_dropout:
  value: 0.4
hidden_size:
  value: 32
learning_rate:
  value: 0.005
num_layers:
  value: 2
