wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: 5
cell_type:
  value: rnn
decoder_dropout:
  value: 0.2
embedding_size:
  value: 64
encoder_dropout:
  value: 0.2
hidden_size:
  value: 128
learning_rate:
  value: 0.0005
num_layers:
  value: 1
use_attention:
  value: false
