wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: null
cell_type:
  value: lstm
decoder_dropout:
  value: 0.2
embedding_size:
  value: 128
encoder_dropout:
  value: 0.5
hidden_size:
  value: 64
learning_rate:
  value: 0.0005
num_layers:
  value: 1
use_attention:
  value: true
