wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 3
cell_type:
  value: lstm
decoder_dropout:
  value: 0.2
embedding_size:
  value: 64
encoder_dropout:
  value: 0.3
hidden_size:
  value: 512
learning_rate:
  value: 0.005
num_layers:
  value: 1
