wandb_version: 1

batch_size:
  value: 32
beam_size:
  value: null
cell_type:
  value: lstm
decoder_dropout:
  value: 0.5
embedding_size:
  value: 256
encoder_dropout:
  value: 0.5
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
num_layers:
  value: 1
