_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 64
beam_size:
    value: 3
cell_type:
    value: lstm
decoder_dropout:
    value: 0.2
embedding_size:
    value: 64
encoder_dropout:
    value: 0.3
hidden_size:
    value: 512
learning_rate:
    value: 0.005
num_layers:
    value: 1
