wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: 5
cell_type:
  value: lstm
decoder_dropout:
  value: 0.2
embedding_size:
  value: 64
encoder_dropout:
  value: 0.2
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
num_layers:
  value: 2
use_attention:
  value: false
