wandb_version: 1

batch_size:
  value: 128
beam_size:
  value: null
cell_type:
  value: gru
decoder_dropout:
  value: 0.3
embedding_size:
  value: 256
encoder_dropout:
  value: 0.5
hidden_size:
  value: 256
learning_rate:
  value: 0.0005
num_layers:
  value: 3
use_attention:
  value: true
