wandb_version: 1

batch_size:
  value: 64
beam_size:
  value: null
cell_type:
  value: gru
decoder_dropout:
  value: 0.2
embedding_size:
  value: 128
encoder_dropout:
  value: 0.5
hidden_size:
  value: 256
learning_rate:
  value: 0.001
num_layers:
  value: 3
use_attention:
  value: true
